#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MatchingGame.Resource", IsApplication=true)]

namespace MatchingGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int black = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Pokemon1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Pokemon10 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Pokemon100 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Pokemon101 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Pokemon102 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Pokemon103 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Pokemon104 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Pokemon105 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Pokemon11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Pokemon12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Pokemon13 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Pokemon14 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Pokemon15 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Pokemon16 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Pokemon17 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Pokemon18 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Pokemon19 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Pokemon2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Pokemon20 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Pokemon21 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Pokemon22 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Pokemon23 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Pokemon24 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Pokemon25 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Pokemon26 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Pokemon27 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Pokemon28 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Pokemon29 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Pokemon3 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Pokemon30 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Pokemon31 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Pokemon32 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Pokemon33 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Pokemon34 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Pokemon35 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Pokemon36 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Pokemon37 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Pokemon38 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Pokemon39 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Pokemon4 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Pokemon40 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Pokemon41 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Pokemon42 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Pokemon43 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Pokemon44 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Pokemon45 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Pokemon46 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Pokemon47 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Pokemon48 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Pokemon49 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Pokemon5 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Pokemon50 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Pokemon51 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Pokemon52 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Pokemon53 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Pokemon54 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Pokemon55 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Pokemon56 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Pokemon57 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Pokemon58 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Pokemon59 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Pokemon6 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Pokemon60 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Pokemon61 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Pokemon62 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Pokemon63 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Pokemon64 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Pokemon65 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int Pokemon66 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int Pokemon67 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int Pokemon68 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Pokemon69 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int Pokemon7 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int Pokemon74 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Pokemon75 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int Pokemon76 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Pokemon77 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int Pokemon78 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int Pokemon79 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int Pokemon8 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int Pokemon80 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int Pokemon81 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int Pokemon82 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int Pokemon83 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int Pokemon84 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int Pokemon85 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int Pokemon86 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int Pokemon87 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int Pokemon88 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int Pokemon89 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int Pokemon9 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int Pokemon90 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int Pokemon91 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int Pokemon92 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int Pokemon93 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int Pokemon94 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int Pokemon95 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int Pokemon951 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int Pokemon96 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int Pokemon97 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int Pokemon98 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int Pokemon99 = 2130837607;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int appScreen = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int first = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int image = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int nextImage = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int original = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int runningScore = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int score = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int second = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int textView = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int third = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
