#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MatchingGame.Resource", IsApplication=true)]

namespace MatchingGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int black = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Pokemon1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Pokemon10 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Pokemon11 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Pokemon12 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Pokemon13 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Pokemon14 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Pokemon15 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Pokemon16 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Pokemon17 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Pokemon18 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Pokemon19 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Pokemon2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Pokemon20 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Pokemon21 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Pokemon22 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Pokemon23 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Pokemon24 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Pokemon25 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Pokemon26 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Pokemon27 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Pokemon28 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Pokemon29 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Pokemon3 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Pokemon30 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Pokemon31 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Pokemon32 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Pokemon33 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Pokemon34 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Pokemon35 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Pokemon36 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Pokemon37 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Pokemon38 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Pokemon39 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Pokemon4 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Pokemon40 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Pokemon41 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Pokemon42 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Pokemon43 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Pokemon44 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Pokemon45 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Pokemon46 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Pokemon47 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Pokemon48 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Pokemon49 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Pokemon5 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Pokemon50 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Pokemon51 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Pokemon52 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Pokemon53 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Pokemon54 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Pokemon55 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Pokemon56 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Pokemon57 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Pokemon58 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Pokemon59 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Pokemon6 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Pokemon60 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Pokemon61 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Pokemon62 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Pokemon63 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Pokemon64 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Pokemon65 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Pokemon66 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Pokemon67 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Pokemon68 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Pokemon69 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Pokemon7 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Pokemon8 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int Pokemon9 = 2130837574;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int appScreen = 2131034112;
			
			// aapt resource value: 0x7f050021
			public const int bestTime = 2131034145;
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int card1 = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int card10 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int card11 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int card12 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int card13 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int card14 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int card15 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int card16 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int card17 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int card18 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int card19 = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int card2 = 2131034116;
			
			// aapt resource value: 0x7f050016
			public const int card20 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int card21 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int card22 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int card23 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int card24 = 2131034138;
			
			// aapt resource value: 0x7f050005
			public const int card3 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int card4 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int card5 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int card6 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int card7 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int card8 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int card9 = 2131034123;
			
			// aapt resource value: 0x7f050020
			public const int completionTime = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int endScreen = 2131034143;
			
			// aapt resource value: 0x7f050001
			public const int gameMap = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int gameMapVoid = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int homeMenu = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int peekAbility = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int startGame = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
